apiVersion: v1
kind: Service
metadata:
  name: module2
  namespace: default
  labels:
    app: module2

spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3838
  selector:
    app: module2
  type: LoadBalancer
