name: Deploy to GKE

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Google Cloud SDK
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@main
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT }}
        export_default_credentials: true

    - name: Configure kubectl
      run: |
        gcloud container clusters get-credentials minh-test-mageai --region europe-north1 --project k8s-test-421812
    - name: Delete job 
      run: |
        kubectl delete -f update_k8s.yaml
    - name: Deploy to GKE
      run: |
        kubectl apply -f update_k8s.yaml